import { useState } from "react";
import { API_MODE, get, post, staticPaper } from "../services";
import type { LoraPrediction, Run } from "../types";

export function LoRAOverview() {
  const paper = staticPaper("lora");
  return <div className="lora-grid"><section className="panel"><div className="eyebrow">PARAMETER-EFFICIENT ADAPTATION</div><h2>Keep the knowledge. Learn a small update.</h2><p>{paper.content.problem}</p><div className="lora-equation">W′ = W₀ + <span>α/r · B A</span></div><div className="lora-flow"><b>Frozen W₀</b><i>+</i><b>Down A → Up B</b><i>→</i><b>Adapted output</b></div><p>Only the low-rank factors receive gradients. At serving time, the adapter can be merged into the dense weight.</p></section><section className="panel"><div className="eyebrow">EVIDENCE BOUNDARY</div><h2>What is measured here?</h2><p>The controlled regression experiment tests equation correctness, gradient isolation, rank capacity, storage accounting, and merge equivalence.</p><p>The paper’s GLUE, GPT-2 and GPT-3 results remain author-reported. This module does not claim to reproduce their benchmark quality.</p><a className="text-link" href={paper.docs.validation}>Validation &amp; assumptions →</a></section></div>;
}

export function LoRAExperiment() {
  const [rank, setRank] = useState(2); const [alpha, setAlpha] = useState(2); const [steps, setSteps] = useState(150); const [run, setRun] = useState<Run | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [input, setInput] = useState("1 0 0 0 0 0 0 0"); const [prediction, setPrediction] = useState<LoraPrediction | null>(null);
  const execute = async () => { setBusy(true); setError(""); setPrediction(null); try {
    const result = await post<Run>("/papers/lora/experiment", { seed: 42, input_dim: 8, output_dim: 6, rank, target_rank: 2, alpha, steps, train_size: 64, eval_size: 16, learning_rate: API_MODE ? .05 : .1 }); setRun(result);
    let next = result;
    while (next.status === "running" || next.status === "queued") { await new Promise(resolve => setTimeout(resolve, 250)); next = await get<Run>(`/papers/lora/results/${result.run_id}`); setRun(next); }
  } catch (exception) { setError(exception instanceof Error ? exception.message : "LoRA experiment failed"); } finally { setBusy(false); } };
  const inspect = async () => { if (!run) return; try { setPrediction(await post<LoraPrediction>("/papers/lora/predict", { run_id: run.run_id, text: input })); } catch (exception) { setError(exception instanceof Error ? exception.message : "Prediction failed"); } };
  const metrics = (run as Run & { metrics?: Record<string, number> } | null)?.metrics ?? run?.test;
  return <div className="lora-grid"><section className="panel"><div className="eyebrow">LORA EXPERIMENT LAB</div><h2>Adapt a frozen dense projection</h2><p>{API_MODE ? "PyTorch controlled adaptation with full fine-tuning and frozen baselines." : "Netlify browser mode: a reduced low-rank matrix adaptation study, not NLP fine-tuning."}</p><div className="control-row"><label>Rank<input type="number" value={rank} min={1} max={6} onChange={event => setRank(Number(event.target.value))}/></label><label>Alpha<input type="number" value={alpha} min={.1} max={20} onChange={event => setAlpha(Number(event.target.value))}/></label><label>Updates<input type="number" value={steps} min={1} max={3000} onChange={event => setSteps(Number(event.target.value))}/></label></div><p>8 input features → 6 output features. Rank {rank} trains {rank * 14} factors versus 48 dense-weight entries; α/r = {(alpha / rank).toFixed(2)}.</p><button className="primary" disabled={busy} onClick={execute}>{busy ? "Training…" : "Run LoRA adaptation"}</button>{run && <div className="run-status"><b>{run.status}</b><span>{run.scientific_status}</span></div>}{metrics && <div className="metric-grid">{Object.entries(metrics).filter(([key]) => key.includes("mse") || key.includes("fraction")).map(([key, value]) => <div key={key}><span>{key.replaceAll("_", " ")}</span><b>{value.toFixed(5)}</b></div>)}</div>}{error && <p role="alert">{error}</p>}</section><section className="panel"><div className="eyebrow">MERGE EQUIVALENCE</div><h2>Inspect the adapted vector</h2><label className="wide-label">Input vector<input value={input} onChange={event => setInput(event.target.value)}/></label><button className="secondary" disabled={!run || run.status !== "completed"} onClick={inspect}>Predict and compare merged output</button>{prediction && <><pre>{prediction.output.map(value => value.toFixed(5)).join(" · ")}</pre><p>Maximum merge difference: {prediction.max_merge_difference.toExponential(3)}</p>{prediction.update_matrix && <MatrixHeatmap matrix={prediction.update_matrix}/>}</>}</section></div>;
}

export function MatrixHeatmap({ matrix }: { matrix: number[][] }) { const maximum = Math.max(...matrix.flat().map(Math.abs), 1e-12); return <div className="matrix-grid" style={{ gridTemplateColumns: `repeat(${matrix[0]?.length || 1},1fr)` }}>{matrix.flat().map((value, index) => <i key={index} title={value.toFixed(6)} style={{ background: value >= 0 ? "#ff6b35" : "#79bbff", opacity: Math.max(.12, Math.abs(value) / maximum) }}/>)}</div>; }

export function LoRAMath() { const equations = staticPaper("lora").content.equations; return <div className="lora-grid">{equations.map(equation => <section className="panel" key={equation.id}><div className="eyebrow">{equation.section}</div><h2>{equation.title}</h2><pre>{equation.equation}</pre><p>{equation.why}</p><p>{equation.example}</p><dl className="facts">{Object.entries(equation.symbols).map(([symbol, explanation]) => <div key={symbol}><dt>{symbol}</dt><dd>{explanation}</dd></div>)}</dl><p>{equation.stability}</p><small>{equation.source}</small></section>)}</div>; }

export function LoRABenchmarks() { const [result, setResult] = useState<unknown>(null); const [busy, setBusy] = useState(false); const measure = async () => { setBusy(true); try { setResult(await post("/papers/lora/benchmark", { input_dim: 128, output_dim: 128, rank: 4, repeats: 30, warmup: 5 })); } finally { setBusy(false); } }; return <section className="panel"><div className="eyebrow">MERGED VS UNMERGED</div><h2>Measure the serving path</h2><p>Compare the parallel low-rank path with a merged dense weight. Browser allocation/timing and PyTorch CPU overhead are recorded separately.</p><button className="secondary" onClick={measure} disabled={busy}>{busy ? "Measuring…" : "Run LoRA benchmark"}</button>{result !== null && <pre>{JSON.stringify(result, null, 2)}</pre>}</section>; }

export function LoRAAlgorithm() { const [step, setStep] = useState(0); const steps = [["Freeze base", "W₀ stays unchanged; optimizer receives only A/B.", "layers.py:mark_only_lora_trainable"], ["Initialize factors", "Random Gaussian A and zero B preserve the base function.", "layers.py:reset_parameters"], ["Run two paths", "h=W₀x+(α/r)BAx combines the base and adapter output.", "layers.py:forward"], ["Optimize adapter", "Backpropagation updates only the low-rank factors.", "runner.py:train_model"], ["Merge for serving", "Wmerged=W₀+(α/r)BA becomes an ordinary dense matrix.", "layers.py:merge"], ["Evaluate", "Compare held-out MSE, parameter counts and merge equivalence.", "runner.py:train"]]; return <section className="panel"><div className="eyebrow">SHOW ME WHAT LORA DOES</div><h2>{step + 1}. {steps[step][0]}</h2><p>{steps[step][1]}</p><pre>{steps[step][2]}</pre><div className="lora-flow"><button className="secondary" onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0}>← Previous</button><span>{step + 1} / {steps.length}</span><button className="secondary" onClick={() => setStep(Math.min(steps.length - 1, step + 1))} disabled={step === steps.length - 1}>Next →</button></div></section>; }

export function LoRALimitations() { return <section className="panel"><div className="eyebrow">SCIENTIFIC HONESTY</div><h2>Where the evidence stops</h2><p>The local study is linear regression, not a pretrained language model. Low rank, target modules and alpha are task-dependent; storage savings do not imply proportional compute savings.</p><p>Full GLUE/GPT-2/GPT-3 reproduction is NOT IMPLEMENTED. The official checkpoints and NLP evaluation scripts remain external.</p><a href={staticPaper("lora").docs.validation} className="text-link">Open validation report →</a></section>; }

export function LoRASource() { const source = staticPaper("lora").source; return <section className="panel"><div className="eyebrow">CODE EXPLORER</div><h2>Inspect the LoRA implementation</h2>{Object.entries(source).map(([path, text]) => <details key={path}><summary><code>{path}</code></summary><pre>{text}</pre></details>)}</section>; }
