"""Common module contract; transport and UI do not implement research logic."""

from typing import Any, Protocol

from research_lab.config import BenchmarkConfig, ExperimentConfig


class ResearchPaperModule(Protocol):
    def metadata(self) -> dict[str, Any]: ...
    def explain(self, level: int) -> list[dict[str, Any]]: ...
    def validate(self) -> dict[str, Any]: ...
    def preprocess(self, config: ExperimentConfig) -> Any: ...
    def train(self, config: ExperimentConfig, run_id: str) -> dict[str, Any]: ...
    def predict(self, run_id: str, text: str, beam_size: int = 1) -> dict[str, Any]: ...
    def evaluate(self, predictions: list[list[str]], targets: list[list[str]]) -> dict[str, float]: ...
    def benchmark(self, config: BenchmarkConfig) -> dict[str, Any]: ...
    def visualize(self, result: dict[str, Any]) -> dict[str, Any]: ...
    def run_experiment(self, config: ExperimentConfig, run_id: str) -> dict[str, Any]: ...
    def get_examples(self) -> list[dict[str, Any]]: ...
    def get_limitations(self) -> list[str]: ...
    def get_references(self) -> list[dict[str, Any]]: ...
