import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { Activity, ArrowRight, BookOpen, BrainCircuit, CheckCircle2, ChevronRight, Cpu, FlaskConical, Gauge, GitBranch, Layers3, Play, RotateCcw, ShieldCheck, Sparkles, XCircle } from "lucide-react";
import "./styles.css";
import "./inspector.css";
import { API_MODE, get, post } from "./services";
import type { Inspection, Paper, Run } from "./types";

const tabs = ["Overview", "Intuition", "Mathematics", "Algorithm", "Architecture", "Experiments", "Benchmarks", "Limitations", "Traceability"];

function Panel({ icon, label, title, children }: { icon: React.ReactNode; label: string; title: string; children: React.ReactNode }) {
  return <section className="panel"><div className="panel-heading"><div className="panel-icon">{icon}</div><div><div className="eyebrow">{label}</div><h2>{title}</h2></div></div>{children}</section>;
}

function App() {
  const [paper, setPaper] = useState<Paper | null>(null); const [tab, setTab] = useState("Overview"); const [level, setLevel] = useState(5);
  const [explanation, setExplanation] = useState<{ title: string; body: string; source?: string }[]>([]); const [error, setError] = useState("");
  const [run, setRun] = useState<Run | null>(null); const [running, setRunning] = useState(false); const [task, setTask] = useState<"reverse" | "copy">("reverse"); const [steps, setSteps] = useState(300); const [input, setInput] = useState("0 1 2 3"); const [inspection, setInspection] = useState<Inspection | null>(null);
  useEffect(() => { get<Paper[]>("/papers").then(items => setPaper(items[0])).catch(e => setError(e.message)); }, []);
  useEffect(() => { if (paper) get<{ title: string; body: string; source?: string }[]>(`/papers/${paper.id}/explanation?level=${level}`).then(setExplanation).catch(e => setError(e.message)); }, [paper, level]);
  useEffect(() => { if (!run || !running) return; const timer = window.setInterval(() => get<Run>(`/papers/attention/results/${run.run_id}`).then(next => { setRun(next); if (next.status === "completed" || next.status === "failed") setRunning(false); }), 1200); return () => window.clearInterval(timer); }, [run, running]);
  const progress = useMemo(() => run?.history?.at(-1)?.step ?? 0, [run]);
  if (!paper) return <main className="loading"><BrainCircuit size={44}/><p>{error || "Loading research lab…"}</p></main>;
  const start = async () => { setError(""); setInspection(null); setRunning(true); try { setRun(await post<Run>(`/papers/${paper.id}/experiment`, { task, steps, seed: 42, train_size: 256, eval_size: 32, batch_size: 32, min_length: 3, max_length: 8, symbols: 12, model: { d_model: 64, heads: 4, layers: 2, d_ff: 128, dropout: 0.1, attention_dropout: 0, positions: "sinusoidal", max_length: 128, optimized: false }, smoothing: 0.1, warmup_steps: 100, learning_rate_factor: 0.5, model_type: "transformer", device: "cpu" })); } catch (e) { setRunning(false); setError(e instanceof Error ? e.message : "Experiment failed"); } };
  const predict = async () => { if (!run || run.status !== "completed") return; try { setInspection(await post<Inspection>(`/papers/${paper.id}/predict`, { run_id: run.run_id, text: input, beam_size: 1 })); } catch (e) { setError(e instanceof Error ? e.message : "Prediction failed"); } };
  return <div className="app"><header className="topbar"><div className="brand"><div className="brand-mark"><Sparkles size={17}/></div><div><strong>RESEARCH LAB</strong><span>paper → product</span></div></div><div className="top-meta"><span className="live-dot"/> LOCAL WORKSPACE <span className="version">v0.1</span></div></header>
    <aside className="sidebar"><div className="side-kicker">PAPER EXPLORER</div><div className="paper-card active"><div className="paper-icon"><BrainCircuit size={22}/></div><div><strong>Attention Is All You Need</strong><small>Neural Architecture · 2017</small></div><CheckCircle2 className="check" size={16}/></div><div className="side-block"><div className="side-kicker">MODULE STATUS</div><div className="status-row"><span>Implementation readiness</span><b>{paper.readiness}%</b></div><div className="meter"><i style={{ width: `${paper.readiness}%` }}/></div><div className="status-row muted"><span>{API_MODE ? "Python API" : "Browser lab"}</span><span className="pill good">active</span></div><div className="status-row muted"><span>WMT reproduction</span><span className="pill amber">partial</span></div></div><div className="side-footer"><ShieldCheck size={15}/> Reproducibility-first<br/><span>Seeds · configs · artifacts recorded</span></div></aside>
    <main className="content"><section className="hero"><div className="eyebrow"><span className="dot"/> NEURIPS 2017 · NLP / SEQUENCE TRANSDUCTION</div><h1>Attention Is<br/><em>All You Need.</em></h1><p className="lede">A research-grade exploration of the Transformer — from the scaled dot-product equation to a runnable, traceable experiment.</p><div className="hero-actions"><button className="primary" onClick={() => { setTab("Experiments"); window.scrollTo({ top: 0, behavior: "smooth" }); }}><FlaskConical size={16}/> Open experiment lab <ArrowRight size={16}/></button><a className="text-link" href={paper.official_url} target="_blank">Read original paper <ChevronRight size={15}/></a></div><div className="hero-stats"><div><b>01</b><span>Attention-only<br/>architecture</span></div><div><b>O(1)</b><span>Dependency<br/>path length</span></div><div><b>28.4</b><span>Reported EN–DE<br/>BLEU <sup>†</sup></span></div><div><b>8×</b><span>Parallel<br/>attention heads</span></div></div></section>
      <nav className="tabs">{tabs.map(item => <button key={item} className={tab === item ? "selected" : ""} onClick={() => setTab(item)}>{item}</button>)}</nav>
      {tab === "Overview" && <Overview paper={paper}/>} {tab === "Intuition" && <Intuition explanation={explanation} level={level} setLevel={setLevel}/>} {tab === "Mathematics" && <Maths/>} {tab === "Algorithm" && <Algorithm/>} {tab === "Architecture" && <Architecture/>} {tab === "Experiments" && <Experiments run={run} running={running} task={task} setTask={setTask} steps={steps} setSteps={setSteps} start={start} progress={progress} input={input} setInput={setInput} predict={predict} inspection={inspection}/>} {tab === "Benchmarks" && <Benchmarks/>} {tab === "Limitations" && <Limitations paper={paper}/>} {tab === "Traceability" && <Traceability/>}
      {inspection && <AttentionInspector inspection={inspection}/>} {error && <div className="error"><XCircle size={16}/>{error}</div>}<footer><span>† Author-reported paper result · not a local reproduction</span><span>{API_MODE ? "Connected to the Python research API." : "Standalone Netlify browser mode · reduced study, not full Transformer training."}</span></footer></main></div>;
}

function Overview({ paper }: { paper: Paper }) { return <div className="grid-two"><Panel icon={<BookOpen size={17}/>} label="THE RESEARCH QUESTION" title="Can we remove recurrence from sequence transduction?"><p>Recurrent and convolutional sequence models make long-range dependencies expensive or sequential. The Transformer proposes an encoder–decoder built entirely from attention, allowing all training positions to be processed in parallel.</p><div className="callout"><b>Central insight</b><br/>Let every position directly choose what to read from every other position.</div></Panel><Panel icon={<Gauge size={17}/>} label="CLAIM STATUS" title="What this lab verifies"><Claim icon={<CheckCircle2/>} title="Verified locally" text="Equations, masks, topology, tied weights, positional encoding, Noam schedule, and deterministic scientific tests."/><Claim icon={<Activity/>} title="Measured here" text="Small synthetic copy/reversal learning, resource benchmarks, ablations, and free-running predictions."/><Claim icon={<GitBranch/>} title="Not claimed" text="Exact WMT14 scores, original BPE pipeline, historical hardware cost, or bitwise reproduction." muted/></Panel><Panel icon={<Layers3 size={17}/>} label="THE ARCHITECTURE" title="Four ideas, one stack"><div className="mini-flow"><span>Tokens</span><ArrowRight/><span>Embeddings<br/><small>+ position</small></span><ArrowRight/><span>Encoder<br/><small>self-attention</small></span><ArrowRight/><span>Decoder<br/><small>causal + cross</small></span><ArrowRight/><span>Next token</span></div></Panel><Panel icon={<GitBranch size={17}/>} label="PAPER FACTS" title="Traceable by design"><dl className="facts"><dt>Authors</dt><dd>Vaswani et al. · Google / Toronto</dd><dt>Venue</dt><dd>NeurIPS 2017 · arXiv 1706.03762</dd><dt>Paper code</dt><dd>Tensor2Tensor · archived Apache-2.0</dd><dt>Key constraint</dt><dd>Full attention is O(n² · d) per layer</dd></dl></Panel></div>; }
function Claim({ icon, title, text, muted }: { icon: React.ReactNode; title: string; text: string; muted?: boolean }) { return <div className={`claim ${muted ? "muted-claim" : ""}`}>{icon}<div><b>{title}</b><span>{text}</span></div></div>; }
function Intuition({ explanation, level, setLevel }: { explanation: { title: string; body: string; source?: string }[]; level: number; setLevel: (n: number) => void }) { return <Panel icon={<Sparkles size={17}/>} label="PROGRESSIVE DISCLOSURE" title="Same mechanism, six lenses"><div className="levelbar">{[0,1,2,3,4,5].map(i => <button className={i === level ? "active" : ""} onClick={() => setLevel(i)} key={i}>0{i}<small>{["Story","Layperson","Beginner","Intermediate","Advanced","Expert"][i]}</small></button>)}</div><div className="explanation-list">{explanation.map((item, i) => <article key={item.title}><span className="number">{String(i + 1).padStart(2, "0")}</span><div><h3>{item.title}</h3><p>{item.body}</p><small className="source-line">{item.source} · {item.title}</small></div></article>)}</div></Panel>; }
function Maths() { return <div className="grid-two"><Panel icon={<Sparkles size={17}/>} label="EQUATION 1 · §3.2.1" title="Scaled dot-product attention"><div className="equation">Attention(Q, K, V) = softmax <span>(QK<sup>T</sup> / √d<sub>k</sub>)</span> V</div><div className="symbol-grid"><div><b>Q · Query</b><span>What this position is looking for.</span></div><div><b>K · Key</b><span>What each position offers for matching.</span></div><div><b>V · Value</b><span>The information that is mixed into output.</span></div><div><b>√d<sub>k</sub></b><span>Prevents large dot products from saturating softmax.</span></div></div><div className="toy-math"><span className="chip">query</span><span>×</span><span className="chip blue">keys</span><span>→ scores →</span><span className="chip green">weights</span><span>× values → output</span></div></Panel><Panel icon={<Cpu size={17}/>} label="EQUATION 3 · §5.3" title="Warmup, then decay"><div className="equation small">lrate = d<sub>model</sub><sup>−0.5</sup> · min(step<sup>−0.5</sup>, step · warmup<sup>−1.5</sup>)</div><p>The paper uses Adam with β₁ = 0.9, β₂ = 0.98, ε = 10<sup>−9</sup> and 4,000 warmup steps. This lab implements the schedule with bounded configurable values for local experiments.</p><div className="curve"><i/><i/><i/><i/><i/><i/><i/><i/></div><small className="caption">Conceptual curve: linear warmup → inverse-square-root decay</small></Panel></div>; }
function Algorithm() { const steps = [["Input", "Token IDs enter the encoder and shifted target IDs enter the decoder."], ["Encode", "Self-attention lets each source position read all non-padding source positions."], ["Decode", "Causal self-attention blocks future target tokens; cross-attention reads encoder memory."], ["Predict", "A tied linear projection produces next-token logits and probabilities."], ["Optimize", "Label-smoothed loss, Adam, and the warmup schedule update parameters."], ["Evaluate", "Teacher-forced loss and free-running exact match/token accuracy are recorded."]]; return <Panel icon={<GitBranch size={17}/>} label="SHOW ME WHAT THE PAPER IS DOING" title="One training example, step by step"><div className="steps">{steps.map(([title, body], i) => <div className="step" key={title}><b>{String(i + 1).padStart(2, "0")}</b><div><h3>{title}</h3><p>{body}</p></div><ChevronRight/></div>)}</div></Panel>; }
function Architecture() { return <Panel icon={<Layers3 size={17}/>} label="MODEL INTERNALS · §3" title="The Transformer encoder–decoder"><div className="architecture"><div className="stack"><strong>ENCODER × N</strong><span>Input embedding<br/>+ sinusoidal PE</span><i>Multi-head self-attention</i><small>Add &amp; Norm</small><i>Position-wise FFN</i><small>Add &amp; Norm</small><span>Memory Z</span></div><div className="bridge"><ArrowRight size={24}/><span>cross-attention</span><ArrowRight size={24}/></div><div className="stack decoder"><strong>DECODER × N</strong><span>Shifted output embedding<br/>+ sinusoidal PE</span><i>Masked self-attention</i><small>Add &amp; Norm</small><i>Encoder–decoder attention</i><small>Add &amp; Norm</small><i>Position-wise FFN</i><small>Add &amp; Norm</small><span>Linear + Softmax</span></div></div></Panel>; }
function Experiments({ run, running, task, setTask, steps, setSteps, start, progress, input, setInput, predict, inspection }: { run: Run | null; running: boolean; task: "reverse" | "copy"; setTask: (t: "reverse" | "copy") => void; steps: number; setSteps: (n: number) => void; start: () => void; progress: number; input: string; setInput: (s: string) => void; predict: () => void; inspection: Inspection | null }) { return <div className="experiment-layout"><Panel icon={<FlaskConical size={17}/>} label="INTERACTIVE EXPERIMENT LAB" title="Train the idea on a controlled task"><p className="panel-intro">Synthetic sequence tasks make the architecture executable on a laptop. They validate the learning pathway, not the paper's WMT score.</p><div className="control-row"><label>Task<select value={task} onChange={e => setTask(e.target.value as "reverse" | "copy")}><option value="reverse">Reverse sequence</option><option value="copy">Copy sequence</option></select></label><label>Training steps<input type="number" min="20" max="5000" value={steps} onChange={e => setSteps(Number(e.target.value))}/></label></div><button className="primary run" onClick={start} disabled={running}>{running ? <><RotateCcw className="spin" size={16}/> Running · {progress} steps</> : <><Play size={16}/> Run seeded experiment</>}</button>{run && <div className="run-status"><span className={`status-dot ${run.status}`}/><b>{run.status}</b><span>{run.scientific_status || "queued"}</span>{run.duration_seconds && <span>{run.duration_seconds.toFixed(1)}s · {run.parameter_count?.toLocaleString()} params</span>}</div>}</Panel><Panel icon={<BrainCircuit size={17}/>} label="INFERENCE + DIAGNOSTICS" title="Inspect a trained run"><label className="wide-label">Input token sequence<input value={input} onChange={e => setInput(e.target.value)} placeholder="0 1 2 3"/></label><button className="secondary" onClick={predict} disabled={!run || run.status !== "completed"}>Generate next tokens <ArrowRight size={15}/></button>{inspection && <div className="prediction"><span>OUTPUT</span>{inspection.tokens.map((token, i) => <b key={`${token}-${i}`}>{token}</b>)}</div>}<div className="metric-grid">{[["Exact match", run?.test?.exact_match], ["Token accuracy", run?.test?.token_accuracy], ["Perplexity", run?.test?.perplexity], ["NLL", run?.test?.nll]].map(([label, value]) => <div key={label as string}><span>{label}</span><b>{typeof value === "number" ? value.toFixed(3) : "—"}</b></div>)}</div></Panel>{run?.history && <Panel icon={<Activity size={17}/>} label="TRAINING CURVE" title="Loss and learning-rate trace"><div className="chart">{run.history.map(point => <div key={point.step} style={{ height: `${Math.max(5, Math.min(96, 100 - point.loss * 12))}%` }} title={`step ${point.step}: loss ${point.loss.toFixed(3)}`}><i/></div>)}</div><div className="chart-axis"><span>step 1</span><span>step {steps}</span></div></Panel>}</div>; }
function Benchmarks() { const [result, setResult] = useState<Record<string, any> | null>(null); const [busy, setBusy] = useState(false); const run = async () => { setBusy(true); try { setResult(await post<Record<string, any>>("/papers/attention/benchmark", { seed: 42, length: 32, batch_size: 4, d_model: 64, heads: 4, repeats: 30, warmup: 5 })); } finally { setBusy(false); } }; return <Panel icon={<Gauge size={17}/>} label="SYSTEMS PERFORMANCE" title="Benchmark the mechanism"><p>Measure the readable attention path against PyTorch scaled-dot-product attention. Results include p50/p95 latency, throughput, parameter bytes, RSS snapshot, analytical attention-matrix bytes, and numerical difference.</p><button className="secondary" onClick={run} disabled={busy}>{busy ? "Measuring…" : "Run measured benchmark"} <Gauge size={15}/></button>{result && <div className="benchmark-result"><div><span>Reference p50</span><b>{result.paths.reference.latency_ms.p50.toFixed(3)} ms</b></div><div><span>SDPA p50</span><b>{result.paths.sdpa.latency_ms.p50.toFixed(3)} ms</b></div><div><span>Max difference</span><b>{result.max_absolute_difference.toExponential(2)}</b></div><div><span>Attention matrix</span><b>{(result.attention_matrix_bytes_fp32 / 1024).toFixed(1)} KB</b></div></div>}<pre>POST /api/papers/attention/benchmark · length=32 · d_model=64 · heads=4</pre></Panel>; }
function AttentionInspector({ inspection }: { inspection: Inspection }) { const layers = inspection.attention.cross || inspection.attention.encoder || []; const matrix = layers.length ? layers[layers.length - 1][0] : []; const max = Math.max(...matrix.flat(), 1e-9); return <Panel icon={<Activity size={17}/>} label="MODEL INTERNALS · DIAGNOSTIC" title="Attention map for the generated prefix"><div className="attention-note">{inspection.confidence_note} {inspection.terminated_with_eos ? "The decoder emitted EOS." : "The bounded generation limit was reached."}</div><div className="attention-wrap"><div className="attention-labels source-labels">{inspection.source_labels.map((label, i) => <span key={`${label}-${i}`}>{label}</span>)}</div><div><div className="attention-grid" style={{ gridTemplateColumns: `repeat(${inspection.source_labels.length}, minmax(10px, 1fr))` }}>{matrix.flatMap((row, y) => row.map((value, x) => <i key={`${y}-${x}`} title={`${inspection.target_labels[y] || "?"} → ${inspection.source_labels[x] || "?"}: ${value.toFixed(3)}`} style={{ opacity: Math.max(.08, value / max) }}/>))}</div><div className="attention-labels target-labels">{inspection.target_labels.map((label, i) => <span key={`${label}-${i}`}>{label}</span>)}</div></div></div><div className="confidence-row"><span>Generated token confidence</span>{inspection.confidence.map((value, i) => <b key={i} title={value.toFixed(5)} style={{ opacity: Math.max(.25, value) }}>{inspection.tokens[i] || "EOS"}</b>)}</div></Panel>; }
function Limitations({ paper }: { paper: Paper }) { const items = ["Full WMT14 EN–DE/EN–FR reproduction is not implemented; the paper's reported BLEU values are shown as author-reported only.", "Whitespace local tokenization differs from the paper's shared BPE/word-piece vocabulary and corpus filtering.", "Full attention has quadratic memory/compute in sequence length; the path-length advantage trades against this cost.", "Greedy/beam inference recomputes decoder prefixes and is a readable reference path, not a production KV-cache implementation.", "Attention distributions are computation diagnostics; they are not automatically faithful explanations."]; return <Panel icon={<ShieldCheck size={17}/>} label="SCIENTIFIC HONESTY" title="Where the evidence stops"><div className="limit-list">{items.map(item => <div key={item}><XCircle size={17}/><span>{item}</span></div>)}</div><a className="text-link" href={paper.official_url} target="_blank">Open validation report <ChevronRight size={15}/></a></Panel>; }
function Traceability() { const rows = [["§3.2.1 Eq. 1 · Attention", "attention.py", "numerical oracle + masks"], ["§3.2.2 · Multi-head", "attention.py", "shape + SDPA equivalence"], ["§3.1 · Encoder/decoder", "model.py", "causal + padding invariants"], ["§3.5 · Positional encoding", "model.py", "explicit values"], ["§5.3 Eq. 3 · Schedule", "training.py", "warmup + decay"], ["§6.1 · Generation", "inference.py", "EOS + beam behavior"], ["§6.2 · Ablations", "runner.py", "seeded local runs"]]; return <Panel icon={<GitBranch size={17}/>} label="PAPER ↔ CODE" title="Follow every substantial claim"><div className="trace-table"><div className="trace-head"><span>PAPER</span><span>IMPLEMENTATION</span><span>VALIDATION</span></div>{rows.map(row => <div className="trace-row" key={row[0]}><span>{row[0]}</span><code>{row[1]}</code><span><CheckCircle2 size={14}/>{row[2]}</span></div>)}</div></Panel>; }

createRoot(document.getElementById("root")!).render(<App/>);
